name: Deploy RBA in AWS

on:
  push:
    #TODO: Only deploying to sandbox (dev branch) during POC. When ready for prod can add main branch and just need to update the github actions production env secrets 
    branches:
      - 'dev'
      - 'tf-setup'

jobs:
  build-and-push-image:
    permissions: write-all
    runs-on: ubuntu-24.04

    environment: ${{ github.ref_name == 'main' && 'Production' || 'Sandbox' }}
    
    steps:
      - name: debug
        run: echo ${{ github.ref_name == 'main' && 'Production' || 'Sandbox' }}
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set global environment variables
        run: |
          cat >> $GITHUB_ENV <<EOF
          TF_STATE_BUCKET_KEY=rba.tfstate
          TF_STATE_BUCKET_REGION=ca-central-1
          TF_VAR_api_key_client=${{secrets.API_KEY}}
          TF_VAR_api_key_secret=${{secrets.API_SECRET}}
          TF_VAR_otp_image_tag=${{ env.IMAGE_TAG || 'latest' }}
          TF_STATE_BUCKET_NAME=${{env.TF_STATE_BUCKET_NAME}}
          TF_VAR_subnet_a=${{vars.TF_VAR_SUBNET_A}}
          TF_VAR_subnet_b=${{vars.TF_VAR_SUBNET_B}}
          EOF

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYER_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Configure terraform backend
        run: |
          cat >"config.tf" <<EOF
          terraform {
            backend "s3" {
              bucket         = "${{ vars.TF_STATE_BUCKET_NAME }}"
              key            = "${{ vars.TF_STATE_BUCKET_KEY }}"
              region         = "${{ vars.TF_STATE_BUCKET_REGION }}"
              use_lockfile   = true
            }
          }
          EOF
        working-directory: ./terraform

      - name: Terraform Init
        id: init
        run: terraform init -upgrade
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./terraform
        continue-on-error: false

      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
      #   working-directory: ./terraform
