name: Deploy RBA in AWS

on:
  push:
    #TODO: Only deploying to sandbox (dev branch) during POC. When ready for prod can add main branch and just need to update the github actions production env secrets 
    branches:
      - 'tf-setup'
      - 'dev'

jobs:
  build-and-push-image:
    permissions: write-all
    runs-on: ubuntu-24.04

    environment: ${{ github.ref_name == 'main' && 'Production' || 'Sandbox' }}
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set global environment variables
        run: |
          cat >> $GITHUB_ENV <<EOF
          TF_STATE_BUCKET_KEY=rba.tfstate
          TF_STATE_BUCKET_REGION=ca-central-1
          TF_VAR_api_key_client=${{secrets.API_KEY}}
          TF_VAR_api_key_secret=${{secrets.API_SECRET}}
          TF_VAR_otp_image_tag=${{ env.IMAGE_TAG }}
          EOF
      
      - name: Set Sandbox environment variables
        if: github.event.inputs.environment == 'Sandbox'
        run: |
          cat >> $GITHUB_ENV <<EOF
          TF_STATE_BUCKET_NAME=risk-based-authn-tf-sandbox
          TF_VAR_subnet_a=Dev-App-A
          TF_VAR_subnet_b=Dev-App-B

      - uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Sandbox Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_DEPLOYER_ROLE_ARN }}
          aws-region: ca-central-1

      - name: Terraform Variables
        run: |
          cat >"config.tf" <<EOF
          terraform {
            backend "s3" {
              bucket         = "${{ env.TF_STATE_BUCKET_NAME }}"
              key            = "${{ env.TF_STATE_BUCKET_KEY }}"
              region         = "${{ env.TF_STATE_BUCKET_REGION }}"
              use_lockfile   = true
            }
          }
          EOF
        working-directory: ./terraform

      - name: Terraform Init
        id: init
        run: terraform init -upgrade
        working-directory: ./terraform

      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color
        working-directory: ./terraform
        continue-on-error: true
